### ISSUE TITLE
[REQUEST] Show map number on Automap

### ISSUE THREAD

**Issue by snoggie1487** [coelckers/prboom-plus#221] opened 2021-02-25 18:09 UTC
As some custom WADs do not have the map number in the custom map names, I would very much appreciate if the map number (e.g. MAP01 or E1M1) would show up in the Automap above the map name.

Thank you for reading.

**Comment by runlow** [comment] 2021-02-26 09:00
Maps in "Back to Saturn X" series for example don't have/show map numbers in `HUSTR_` which makes it more difficult for me to `-warp` to levels from command line, so I think this would be useful.

Something to note is that prboom-plus outputs the map number to STDOUT when the level starts and you can filter it out by appending `2>/dev/null | grep MAP` to the command (that's one of the ways I used to try to get the map number, on windows you need cygwin for this).

Another way was trying to memorise/guess which map it is and then checking it with the `IDCLEV` cheat.

Neither method is super convenient. I can understand though why adding this could add to "feature creep".

Maybe _prepending_ the _number-to-type for the cheat or use as an argument for `-warp`_ to the string shown at the bottom of the screen in automap would be a simpler implementation introducing less clutter?

Another way to go about it could be to add it to the output of the `IDMYPOS` cheat or one of the other cheats?

**Comment by fabiangreffrath** [comment] 2021-02-26 09:04
I could check if the map name string starts with a map identifier (e.g. ExMy or MAPxy) as in the IWADs and if not, add this to the string, However, this *must* be optional, because (a) this second-guesses the map author's choice not to show the map identifier in the automap and (b) people hate UI clutter.

**Comment by fabiangreffrath** [comment] 2021-02-26 09:55
It makes a difference if you set "status bar and menu appearance" to "not adjusted" or "doom format". I have the former setting and t doesn't work with your patch - if I switch to the latter, it does.

**Comment by runlow** [comment] 2021-02-27 10:48
Checking if the `HUSTR_` contains an identifier and adding an extra option for it sounds like going a bit too far to me.

How about if `IDCLEV` displayed the current level similar to how `IDBEHOLD` shows a menu before you finish the cheat?

So you'd be typing `IDCLEV` and the "menu" would say `CURRENT: MAP01` or `CURRENT: 01` and then as you type in the remaining two digits it would warp as normal.

This could be the default behaviour and then there would be no need for adding an extra option in config or for cluttering the automap. It also would be (somewhat) consistent with how the cheats already work.

**Comment by fabiangreffrath** [comment] 2021-02-27 12:26
@snoggie1487 Do you agree with @runlow's idea?

**Comment by JadingTsunami** [comment] 2021-02-27 15:25
It's a good compromise. Since this is a UMAPINFO port, I think the modified cheat should show current, next and nextsecret (if set).

**Comment by snoggie1487** [comment] 2021-02-27 22:34
Sure, that sounds good.

**Comment by fabiangreffrath** [comment] 2021-03-01 11:52
> It's a good compromise. Since this is a UMAPINFO port, I think the modified cheat should show current, next and nextsecret (if set).

He, what does one have to do with the other?

**Comment by JadingTsunami** [comment] 2021-03-01 15:12
> > It's a good compromise. Since this is a UMAPINFO port, I think the modified cheat should show current, next and nextsecret (if set).
> 
> He, what does one have to do with the other?

I was thinking of the use case "I need to know which map I'm on to use IDCLEV/warp", where map ordering is significant (i.e., I want to move to the next map in the sequence, because I'm stuck on this one and want to proceed without finishing it).

Which makes me realize, maybe the even better answer is to just have a "next/nextsecret map" cheat for that use case. :)

**Comment by fabiangreffrath** [comment] 2021-03-01 15:14
> Which makes me realize, maybe the even better answer is to just have a "next/nextsecret map" cheat for that use case. :)

We even have a key binding for this already.

**Comment by JadingTsunami** [comment] 2021-03-01 15:19
> > Which makes me realize, maybe the even better answer is to just have a "next/nextsecret map" cheat for that use case. :)
> 
> We even have a key binding for this already.

Right, not for nextsecret though. I'm just wondering if it makes the most sense to merge level identifying and switching functionality into IDCLEV.

**Comment by fabiangreffrath** [comment] 2021-03-01 15:27
> Right, not for nextsecret though.

I beg to differ: 
https://github.com/coelckers/prboom-plus/blob/af274b2344d2ba2a630206d8d784a78a4de85204/prboom2/src/e6y.c#L416

**Comment by JadingTsunami** [comment] 2021-03-01 15:35
Oh interesting, I didn't realize it worked that way.

I still wonder if users would find this functionality easier to find and use if it were merged into a numberless version of IDCLEV.

**Comment by fabiangreffrath** [comment] 2021-03-01 15:43
The problem is that secret exists (and map trsnsitions per-se) are hard-coded for non-UMAPINFO maps, so I would have to either duplicate all of this information in the IDCLEV cheat ("boo!") or restrict showing this information for UMAPINFO maps only ("also boo!") .

**Comment by JadingTsunami** [comment] 2021-03-01 16:49
> The problem is that secret exists (and map trsnsitions per-se) are hard-coded for non-UMAPINFO maps, so I would have to either duplicate all of this information in the IDCLEV cheat ("boo!") or restrict showing this information for UMAPINFO maps only ("also boo!") .

Hmm, I would refactor to functions that returned nextmap and nextsecret. That would abstract that information out from both the cheat and the keybind, and make it available for other uses too.

But, I am curious if anyone would find this useful or it's just my viewpoint. If the keybind is fulfilling the requirement nicely for everyone, I don't want to sidetrack things.

**Comment by fabiangreffrath** [comment] 2021-03-01 17:48
Let's please focus on the "which map am I on?" part. After all, you could type IDCLEV to check your current map, then hit the "next level" key and type IDCLEV again.

**Closed** 2021-03-04 14:02 UTC
Labels: pending

**Comment by runlow** [comment] 2021-03-13 10:41
Works well. Big thanks for implementing this!
