### ISSUE TITLE
Getting a segfault on exit with "show endoom screen" option enabled

### ISSUE THREAD

**Issue by TwelveEyes** [coelckers/prboom-plus#191] opened 2021-02-10 20:36 UTC
Like the title says, I've been getting a segfault error upon exiting prboom-plus with the "show endoom screen" option enabled. This is on a debug build of commit [24afe0b](https://github.com/coelckers/prboom-plus/commit/24afe0b80d8794be8cc104908ddd7a96b38acb3a) running on Debian stable (Buster).

The gdb backtrace shows this:
![2021-02-10_12-20](https://user-images.githubusercontent.com/18486153/107568179-7e6b5b80-6b9b-11eb-9368-12ba27abc3c4.png)

It looks like it errors at line 238 in TXT_Init() which is simply:
`if (SDL_Init(SDL_INIT_VIDEO) < 0) { return 0; }`

I'm at a total loss as to why SDL is exploding when initialized. Any help or pointers would be greatly appreciated.

**Comment by fabiangreffrath** [comment] 2021-02-11 09:35
I'll try to reproduce this later today, but from the backtrace you provided, it seems like the segfault occured somewhere in the depths of your radeon video driver. Let's see if I come to a similar result with my Intel graphics.

**Comment by fabiangreffrath** [comment] 2021-02-11 11:11
Unreproducible on my system (Debian testing/unstable) with the following graphics controller:

```
00:02.0 VGA compatible controller: Intel Corporation UHD Graphics 620 (Whiskey Lake)
```

Out of curiosity, does Chocolate Doom also crash when it shows the ENDOOM screen?

**Comment by alexey-lysiuk** [comment] 2021-02-11 13:18
It seems to crash inside LLVM which is used for compiling shaders.
The problem is, debugging anything without symbols is really tedious.
I would suggest to build debug version of SDL2, and link PrBoom+ with it instead of system one.
This may give some hints what triggers the crash.

**Comment by fabiangreffrath** [comment] 2021-02-11 13:34
Or, since you are on Debian, please install the `libsdl2-2.0-0-dbgsym` package from http://debug.mirrors.debian.org/debian-debug/pool/main/libs/libsdl2/.

**Comment by TwelveEyes** [comment] 2021-02-11 16:54
I tested the Debian provided chocolate-doom package (v3.0.0) and the endoom screen displays without any problems, which is interesting. Eternity also displays the endoom without issue. I'll install libsdl2-2.0-0-dbgsym later today and do another backtrace.

**Comment by TwelveEyes** [comment] 2021-02-11 17:22
Here is the backtrace with SDL2 debug symbols. I'm not sure how helpful it is.

![2021-02-11_09-13](https://user-images.githubusercontent.com/18486153/107672732-1c1d6400-6c4a-11eb-9b03-e0b95e97e522.png)

**Comment by fabiangreffrath** [comment] 2021-02-11 22:32
Please add a breakpoint on `I_Quit()` and tell me if it gets called twice during shutdown.

**Comment by TwelveEyes** [comment] 2021-02-11 23:24
Looks like `I_Quit()` only gets called once on shutdown, endoom enabled or not.

![2021-02-11_15-18](https://user-images.githubusercontent.com/18486153/107711544-b0082380-6c7c-11eb-86cc-6737f052c481.png)

![2021-02-11_15-23](https://user-images.githubusercontent.com/18486153/107711849-2e64c580-6c7d-11eb-90e4-e0148b6e6b0e.png)

**Comment by fabiangreffrath** [comment] 2021-02-12 07:37
I could provoke a crash with a similar backtrace when setting `SDL_VIDEODRIVER=wayland`. Any chance your SDL2 is using the wayland backend?

**Comment by fabiangreffrath** [comment] 2021-02-12 09:38
More questions: Does this only happen if you have "Video Mode" set to "OpenGL"? If yes, does this only happen if you have "Sector Light Mode" set to "Shaders"?

**Comment by fabiangreffrath** [comment] 2021-02-12 10:55
Random idea, before I forget it. Dies this make a difference?
```
--- a/prboom2/src/SDL/i_video.c
+++ b/prboom2/src/SDL/i_video.c
@@ -497,6 +497,8 @@ void I_ShutdownGraphics(void)
 {
   SDL_FreeCursor(cursors[1]);
   DeactivateMouse();
+
+  if (sdl_glcontext) SDL_GL_DeleteContext(sdl_glcontext);
 }
 
 //
```

**Comment by TwelveEyes** [comment] 2021-02-12 17:39
> Any chance your SDL2 is using the wayland backend?

No, SDL is using x11.

> More questions: Does this only happen if you have "Video Mode" set to "OpenGL"?

No, it happens on all video modes.

> Random idea, before I forget it. Dies this make a difference?
> 
> ```
> ...
> +  if (sdl_glcontext) SDL_GL_DeleteContext(sdl_glcontext);
> ...
> ```

Unfortunately, no change.

**Comment by TwelveEyes** [comment] 2021-02-14 06:18
Well, I didn't solve the problem, merely sidestepped it by forcing prboom-plus to use the llvmpipe instead of the radeonsi mesa driver by using the environment variable `LIBGL_ALWAYS_SOFTWARE=true`. The ENDOOM displays normally with llvmpipe. Still don't know what is wrong with the radeonsi mesa driver.

**Comment by fabiangreffrath** [comment] 2021-02-15 09:17
Alright, yo if this turns out to be a driver issue, I guess there isn't much we can do about it from the game engine side. Please consider closing this bug then, thanks!

**Closed** 2021-02-15 18:25 UTC
