### ISSUE TITLE
Fix sky in Eviternity.wad (opengl render)

### ISSUE THREAD

**Issue by JuanchoES** [coelckers/prboom-plus#206] opened 2021-02-16 14:35 UTC
The sky looks wrong, but looks correct in sofware mode

**Comment by fabiangreffrath** [comment] 2021-02-17 07:56
Which map do you mean? IIRC Eviternity has a custom sky for about every map. What do you mean with "wrong" and "correct", please elaborate. How about screenshots?

**Comment by PhoxFyre** [comment] 2021-02-17 08:36
Also which version are you using? As you have "(Glboom+)" in your issue title, I think you may be using 2.5.1.4 or 2.5.1.5.test which have the glboom-plus.exe included, whereas the latest here (2.6um) only has prboom-plus.exe included and internal setting to change to OpenGL. This may be a tangential aside, but please make sure you are using the current most up-to-date version as 2.5.1.4 and 2.5.1.5.test are not within the realms of the development of this repo.

**Comment by JuanchoES** [comment] 2021-02-17 12:10
im using this version https://github.com/coelckers/prboom-plus/releases/tag/v2.6um sorry for the video quality 


https://user-images.githubusercontent.com/70743149/108202442-678bb280-7121-11eb-9428-c41def18dfcb.mp4

**Comment by jackrjli** [comment] 2021-02-17 20:12
In your config file, what is the value of gl_skymode? Try setting that to 3 if it isn't.

**Comment by JuanchoES** [comment] 2021-02-17 20:17
> In your config file, what is the value of gl_skymode? Try setting that to 3 if it isn't.

It works! Should i keep this setting forever? Whats the differences between the other settings of "gl_skymode"? Thx
![image](https://user-images.githubusercontent.com/70743149/108262581-65e3de00-7165-11eb-8ce6-69a2729c1ede.png)

**Comment by jackrjli** [comment] 2021-02-18 08:52
I don't know what exactly gl_skymode does, but I haven't run into any problems keeping it on 3. That said, it doesn't solve _all_ problems the GL renderer has with skies (for example, the skies in Ancient Aliens are misaligned no matter what skymode you use, most noticeably in the last few maps).

**Comment by fabiangreffrath** [comment] 2021-02-18 09:38
`gl_skymode` being set to `0`, which is the default, means `skytype_auto` [1], which in turn means `skytype_skydome` if mouselook is enabled or `skytype_standard` if it isn't [2]. Setting `gl_skymode` to `3` permanently sets it to `skytype_skydome`. Don't ask me what the difference is, though...


[1] https://github.com/coelckers/prboom-plus/blob/995b06347f6db3745fe877f5d826571435f03db1/prboom2/src/gl_struct.h#L52-L60
[2] https://github.com/coelckers/prboom-plus/blob/995b06347f6db3745fe877f5d826571435f03db1/prboom2/src/e6y.c#L486-L491

**Comment by runlow** [comment] 2021-02-28 09:59
`gl_skymode` when set to `3` (skytype_skydome) seems to be meant for mouselook.
The edges of the sky "bend" as you turn left and right.
Strangely when it's set to `0` and I toggle mouse look in Eviternity map01 with the `\` key the sky still seems broken.

When set to `2` it just scrolls left and right in a plain way (vanilla sky behaviour) afaik. As if moving a piece of paper left and right - no "bending". (still appears broken though in Eviternity).

In "8bit" video mode the sky seems to work as expected except when I try to toggle mouse look.

@jackrjli 
When you set `gl_skymode` to `3` for **everything** the sky doesn't work the way it does in the vanilla game (edges of the sky are bent with that setting - with or without mouse look, while in vanilla they are not).

**Comment by JadingTsunami** [comment] 2021-04-08 21:40
The setting `render_stretchsky` in the PrBoom config file should be set to `1` to resolve issues like this. This will ensure that non-standard sky sizes get "stretched" to fill the view.

**Comment by Kappa971** [comment] 2021-04-08 22:10
Software render:
![Prboom-plus Screenshot 2021 04 08 - 23 59 29 02](https://user-images.githubusercontent.com/62349018/114102345-6f690700-98c7-11eb-88b5-2d92fd2ea79c.png)
Opengl render with gl_skymode 0
![Prboom-plus Screenshot 2021 04 08 - 23 59 39 99](https://user-images.githubusercontent.com/62349018/114102386-7d1e8c80-98c7-11eb-812a-e4736a975382.png)
Opengl render with gl_skymode 3
![Prboom-plus Screenshot 2021 04 09 - 00 05 46 44](https://user-images.githubusercontent.com/62349018/114102404-89a2e500-98c7-11eb-8c2c-d6cc30bf87d0.png)
Only the first screenshot (software render) is displayed correctly. render_stretchsky was already set to 1

**Comment by JadingTsunami** [comment] 2021-04-08 23:58
@Kappa971 I'm not able to reproduce what you are seeing. What are your display settings?

**Comment by Kappa971** [comment] 2021-04-09 09:08
This is my config file: 
[prboom-plus.txt](https://github.com/coelckers/prboom-plus/files/6284520/prboom-plus.txt)

**Comment by JadingTsunami** [comment] 2021-04-09 18:11
Thanks. From your configuration I was able to isolate the issue. I have a fix for this, I will create a PR later.

**Comment by Kappa971** [comment] 2021-04-09 18:40
I'm glad I was helpful, thanks

**Closed** 2021-04-12 09:25 UTC
Labels: OpenGL
