### ISSUE TITLE
-noload skips loading prboom-plus.wad

### ISSUE THREAD

**Issue by jackrjli** [coelckers/prboom-plus#324] opened 2021-06-03 08:47 UTC
There's a -noload parameter to skip loading the wads listed in the options menu ("Files preloaded at game startup"), but using it also skips loading prboom-plus.wad, resulting in failure to start ("W_GetNumForName: CRBRICK not found"). This is because prboom-plus.wad is added to the same array that holds the list of wads to preload: https://github.com/coelckers/prboom-plus/blob/751badbd0738d9521ca530f77f1bc053370536d7/prboom2/src/m_misc.c#L1717

**Comment by fabiangreffrath** [comment] 2021-06-07 06:17
I understand your issue and the fix would be fairly simple. But I wonder if we should really expect the engine to autoload its own resource WAD file if we explicitly asked it not to autoload *any* WAD file at all. I can even imagine this behavior to be quite useful if one is e.g. going to test a different version of the prboom-plus.wad file and wants to make sure it is not diluted with a previously installed version.

**Comment by fabiangreffrath** [comment] 2021-06-07 06:19
This could be a possible patch:
```patch
--- a/prboom2/src/d_main.c
+++ b/prboom2/src/d_main.c
@@ -1807,11 +1841,15 @@ static void D_DoomMainSetup(void)
   // Designed to be general, instead of specific to boomlump.wad
   // Some people might find this useful
   // cph - support MBF -noload parameter
-  if (!M_CheckParm("-noload")) {
+  {
     // only autoloaded wads here - autoloaded patches moved down below W_Init
-    int i;
+    int i, imax = MAXLOADFILES;
 
-    for (i=0; i<MAXLOADFILES; i++) {
+    // make sure to always autoload prboom-plus.wad
+    if (M_CheckParm("-noload"))
+      imax = 1;
+
+    for (i=0; i<imax; i++) {
       const char *fname = wad_files[i];
       char *fpath;
 ```

**Comment by JadingTsunami** [comment] 2021-06-07 16:30
It does seem like we lose useful functionality if there is absolutely no way to skip loading the default `prboom-plus.wad`.

One option might be to add documentation for this command line parameter in `README.command-line`. Right now it's listed but the behavior is not defined.

That said, the original intent from `MBF.txt` (below) appears to be to skip preloaded WADs only, and presumably any WAD required for operation wouldn't have been included under that umbrella (which would make this a genuine bug).

```
* Menu option to load up to two WAD and two DEH/BEX files at program startup
  + -noload command-line override switch
```

**Comment by fabiangreffrath** [comment] 2021-06-08 07:25
This isn't exactly comparable to MBF, because this had all the lumps that are in `prboom-plus.wad` nowadays built right into the executable (in `info.c`). So, MBF would load its supplemental assets even if the `-noload` parameter was given - which doesn't match what Pr+ currently does and is what the OP requested.

**Comment by JadingTsunami** [comment] 2021-06-08 14:56
> This isn't exactly comparable to MBF, because this had all the lumps that are in `prboom-plus.wad` nowadays built right into the executable (in `info.c`). So, MBF would load its supplemental assets even if the `-noload` parameter was given - which doesn't match what Pr+ currently does and is what the OP requested.

Right, my point being, if we accept the premise that `-noload` was intended as the opposite of "preload", then this is a genuine bug and I think the patch you proposed should be merged in.

**Comment by jackrjli** [comment] 2021-06-09 00:57
> I understand your issue and the fix would be fairly simple. But I wonder if we should really expect the engine to autoload its own resource WAD file if we explicitly asked it not to autoload _any_ WAD file at all. I can even imagine this behavior to be quite useful if one is e.g. going to test a different version of the prboom-plus.wad file and wants to make sure it is not diluted with a previously installed version.

Good point, loading prboom-plus.wad would contradict what the parameter name "noload" seems to imply. But on the other hand, as already discussed, the current behavior is inconsistent with the feature as inherited from MBF.

I can see merit in either interpretation, though my personal use case for this feature favors how it's described in MBF.txt. I found this parameter because I was looking for a convenient way to autoload cosmetic wads when playing casually, but skip loading them when recording demos for DSDA, which disallows sprite modifications. To that end, I was considering extending this parameter to skip the autoload directory, in addition to the wads listed in the config. Chocolate Doom has the `-noautoload` parameter for this, but PrBoom+'s implementation lacks this.

**Comment by fabiangreffrath** [comment] 2021-06-09 06:43
So, may I assume we have reached consensus that `prboom-plus.wad` is not just another PWAD but an integral part of the engine and should thus always get autoloaded, even if `-noload` is passed? Additionally, this would make the whole implementation consistent with the documentation.

**Comment by jackrjli** [comment] 2021-06-09 07:19
> So, may I assume we have reached consensus that `prboom-plus.wad` is not just another PWAD but an integral part of the engine and should thus always get autoloaded, even if `-noload` is passed? Additionally, this would make the whole implementation consistent with the documentation.

Sounds good to me at least.

**Closed** 2021-06-14 06:06 UTC
Labels: patch, question
