### ISSUE TITLE
Please make the software renderer more optimized

### ISSUE THREAD

**Issue by skyrain128** [coelckers/prboom-plus#310] opened 2021-05-15 03:15 UTC
I never seen software renderer over 130FPS.
When using OpenGL mode, the framerate is over 4700+ FPS, but in software mode, the framerate doesn't over 130FPS....
Resolution is 2560x1440.

**Comment by JuanchoES** [comment] 2021-05-17 00:56
I have heard that in some older versions of prboom+ software rendering was much better, but nobody knows why.

**Comment by maxmanium** [comment] 2021-05-24 20:30
I've noticed this too -- on my weaker laptop, the software renderer gets 50-55 fps on Entryway. Enabling exclusive fullscreen does give a slight boost but not much (~10 fps).

**Comment by JadingTsunami** [comment] 2021-05-28 01:06
Dupe of #265

**Comment by fabiangreffrath** [comment] 2021-05-29 10:14
> Dupe of #265

**Closed by fabiangreffrath** 2021-05-29 10:14 UTC
