### ISSUE TITLE
[REQUEST] Walk over / under monsters

### ISSUE THREAD

**Issue by snoggie1487** [coelckers/prboom-plus#220] opened 2021-02-25 17:58 UTC
One of my favorite features in other sourceports is the option to walk over / under monsters. I am not that versed into how demo compatibility works, but I know Crispy Doom strives for vanilla demo compatibility, and still has this option.

Thank you for reading.

**Comment by fabiangreffrath** [comment] 2021-02-26 09:01
Crispy Doom entirely disables this during demo recording and playback. There is *no way* to implement this in a demo-compatible manner otherwise. 

That being said, it is very unlikely this feature makes it into PrBoom+, because not only it is contrary to its mission goal (i.e. demo compatibility above all), but there is also no reasonable reference implementation available. The solution in Crispy is a bit too naive and fails to properly handle e.g. vertical movement [1, 2]. The only canonical implementation that I can think of is in Heretic and porting this to PrBoom+ would be  massive change, that would probably bring more risk than benefit. But, speaking of Heretic, maybe @kraflab has something to add here?

[1] https://github.com/fabiangreffrath/crispy-doom/issues/381
[2] https://github.com/fabiangreffrath/crispy-doom/issues/703

**Comment by runlow** [comment] 2021-02-26 10:10
Related: https://youtu.be/7SE7BIPe3Qs?t=715
This link shows/explains the impact which removing infinite height can have on gameplay.

Zdoom-based sourceports **already** provide this kind of over-the-top stuff plus much more. Not sure I see much point in having this implemented in prboom-plus - especially if/since it could compromise things it's doing well (which are the reason some of us are using it in first place).

**Comment by kraflab** [comment] 2021-02-26 13:56
> But, speaking of Heretic, maybe @kraflab has something to add here?

I think you've already covered it basically. There's no "implement finite height" commit from dsda-doom that you could just cherry-pick for instance because the effects show up in many places. An example of that is in the code for melee range: https://github.com/kraflab/dsda-doom/blob/163435662a84b975e1e47d04dc5d40fa210a6978/prboom2/src/p_enemy.c#L161

You could scour the heretic code base to copy its implementation of all the collision code but there are a lot of complications in that code in pr+ with branching conditions based on compatibility. You would need to make sure someone playing a wad in any compatibility still has expected behaviour for finite height. I think it's out of scope.

**Closed** 2021-03-13 05:32 UTC
Labels: invalid
